version: '3.7'

services:
  next-app:
    build:
      context: ./
      dockerfile: ./dockerfile
    container_name: healfoodcz-web-next
    restart: always
    networks:
      - my-network

networks:
  my-network:
    external: true
