#!/usr/bin/env sh

# exit if error happens
set -e

# go to project root
cd "$( cd "$(dirname "$0")" ; pwd -P )"
cd "../"

# compose the container
docker-compose --project-name healfoodcz down --remove-orphans

# clear unused images
docker image prune -f
