#!/usr/bin/env sh

# exit if error happens
set -e

# go to project root
cd "$( cd "$(dirname "$0")" ; pwd -P )"
cd "../"

# stop and remove the container
docker stop web-next
docker rm web-next

# clear unused images
docker image prune -f
