#!/usr/bin/env sh

# go to project root
cd "$( cd "$(dirname "$0")" ; pwd -P )"
cd "../"

# load .env file
if [ -f .env ]; then
    set -o allexport
    . ./.env
    set +o allexport
fi

# make sure the previous container is down
./cli/down

# login hub.docker.com
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# make sure the image is up to date
docker pull "$DOCKER_REPOSITORY"

# run the container
docker run --detach --restart always --network my-network --name web-next "$DOCKER_REPOSITORY:latest"

# logout hub.docker.com
docker logout
