#!/usr/bin/env sh

# go to project root
cd "$( cd "$(dirname "$0")" ; pwd -P )"
cd "../"

# make sure previous container is down
./cli/down

# compose the container
docker-compose --project-name healfoodcz up --detach --build
